# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapp', '0003_auto_20170811_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
