# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmpw',
            new_name='comfirmpw',
        ),
    ]
