# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregapp', '0002_auto_20170814_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='comfirmpw',
            new_name='confirmpw',
        ),
    ]
